### ISSUE TITLE
Add callable command to get verification DM 

### ISSUE THREAD

**Issue by gabrc52** [sipb/wide-tim#4]
/verify should send you a verification DM (in case the bot was dead when you joined or something)

To have a modern bot, we need to learn how to use slash commands, otherwise a simple "on message received" event should work just to have something functional.

**Comment by 01110011011101010110010001101111** [comment]
Updated in 1d1c387a0ede159f5350d82f8bf37cf00a4768fd.

**Comment by 01110011011101010110010001101111** [comment]
Updated to slash commands in 03e044efafe813a2b39b7ff2d091eafb172e88bf.
