### ISSUE TITLE
Fix up strings

### ISSUE THREAD

**Issue by gabrc52** [sipb/wide-tim#5]
Check that all strings and messages are complete (follow the gist of what Petey said, ensure consistency, not too much redundancy, not too lengthy). Places that may need to be changed:

* Messages during the verification flow on verify2027.php
* The emails that are sent
* The DMs that are sent

**Comment by 01110011011101010110010001101111** [comment]
Worked on updating the flow and making sure everything looks right, so closing for now. See linked PR and other commits.
